/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  NewAccount: () => import('#controllers/new_account_controller'),
  News: () => import('#controllers/news_controller'),
  Session: () => import('#controllers/session_controller'),
}
